name: pipeline

on: [push, pull_request]

jobs:
  pipeline:
    name: pipeline
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [18, 19]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 7.x.x

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Install and build
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: |
          pnpm format
          pnpm lint

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    name: publish
    needs: pipeline
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 7.x.x

      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Install and build
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/v')
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
