name: pipeline

on: [push, pull_request]

jobs:
  pipeline:
    name: pipeline
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [16, 17]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.x.x

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Install and build
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: |
          pnpm format
          pnpm lint

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
